-- Run this in your Supabase SQL Editor

-- Profiles table (one row per user, auto-created on sign-up)
create table public.profiles (
  id          uuid references auth.users(id) on delete cascade primary key,
  username    text unique,
  created_at  timestamptz default now()
);

-- Secure it: users can only read/write their own profile
alter table public.profiles enable row level security;

create policy "Users can view their own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Auto-create a profile row when a new user signs up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id)
  values (new.id);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ─────────────────────────────────────────────────────────────
-- GAMES
-- One row per match. board_layout stores the randomly generated
-- square-to-category assignments for that game.
-- ─────────────────────────────────────────────────────────────
create table public.games (
  id           uuid primary key default gen_random_uuid(),
  status       text not null default 'waiting'
                 check (status in ('waiting', 'active', 'completed')),
  winner_id    uuid references public.profiles(id) on delete set null,
  board_layout jsonb,
  created_at   timestamptz default now()
);

alter table public.games enable row level security;

-- ─────────────────────────────────────────────────────────────
-- GAME PLAYERS
-- One row per player per game. Tracks position, health,
-- which checkpoints they've cleared, and whose turn it is.
-- ─────────────────────────────────────────────────────────────
create table public.game_players (
  id                  uuid primary key default gen_random_uuid(),
  game_id             uuid not null references public.games(id) on delete cascade,
  player_id           uuid not null references public.profiles(id) on delete cascade,
  position            text not null default 'center',
  health              integer not null default 3 check (health >= 0),
  checkpoints_cleared text[] not null default '{}',
  turn_order          integer not null check (turn_order between 1 and 4),
  is_current_turn     boolean not null default false,
  joined_at           timestamptz default now(),
  unique (game_id, player_id),
  unique (game_id, turn_order)
);

alter table public.game_players enable row level security;

-- ─────────────────────────────────────────────────────────────
-- POLICIES
-- Added after both tables exist so cross-table references work.
-- ─────────────────────────────────────────────────────────────

-- Games: players can only see games they're in
create policy "Players can view their own games"
  on public.games for select
  using (
    exists (
      select 1 from public.game_players
      where game_id = games.id and player_id = auth.uid()
    )
  );

-- Game players: members can see all rows for their game
create policy "Players can view game_players in their games"
  on public.game_players for select
  using (
    exists (
      select 1 from public.game_players gp
      where gp.game_id = game_players.game_id and gp.player_id = auth.uid()
    )
  );

-- Game players: each player can update only their own row
create policy "Players can update their own game_player row"
  on public.game_players for update
  using (player_id = auth.uid());

-- ─────────────────────────────────────────────────────────────
-- QUESTIONS
-- The question bank. All generated by Claude.
-- category matches the 6 board categories.
-- ─────────────────────────────────────────────────────────────
create table public.questions (
  id             uuid primary key default gen_random_uuid(),
  category       text not null
                   check (category in ('science','history','geography',
                                       'entertainment','sports','art_lit')),
  body           text not null,
  correct_answer text not null,
  wrong_answers  text[] not null check (array_length(wrong_answers, 1) = 3),
  created_at     timestamptz default now()
);

alter table public.questions enable row level security;

create policy "Authenticated users can read questions"
  on public.questions for select
  using (auth.role() = 'authenticated');

-- ─────────────────────────────────────────────────────────────
-- TURNS
-- Full log of every move in every game.
-- question_id is null for roll-again squares (no question served).
-- ─────────────────────────────────────────────────────────────
create table public.turns (
  id                 uuid primary key default gen_random_uuid(),
  game_id            uuid not null references public.games(id) on delete cascade,
  player_id          uuid not null references public.profiles(id) on delete cascade,
  from_position      text not null,
  to_position        text not null,
  question_id        uuid references public.questions(id) on delete set null,
  answered_correctly boolean,
  created_at         timestamptz default now()
);

alter table public.turns enable row level security;

create policy "Players can view turns in their games"
  on public.turns for select
  using (
    exists (
      select 1 from public.game_players
      where game_id = turns.game_id and player_id = auth.uid()
    )
  );

create policy "Players can insert their own turns"
  on public.turns for insert
  with check (player_id = auth.uid());
